site_name: Azgaarnoth
site_url: http://azgaarnoth.tedneward.com/
nav:
  - 'World':
    - Geography: Geography
    - Religions: Religions
    - Nations: Nations
    - Cities: Cities
    - Cultures: Cultures
    - 'Organizations':
      - Overview: Organizations
      - Bardic Colleges: Organizations/BardicColleges
      - Dueling Colleges: Organizations/DuelingColleges
      - Great Houses: Organizations/Houses
      - Mage Schools: Organizations/MageSchools
      - Merchant Guilds: Organizations/MerchantGuilds
      - Militant Orders: Organizations/MilitantOrders
      - Monastic Orders: Organizations/MonasticOrders
      - Rogues' Guilds: Organizations/RoguesGuilds
    - 'History':
      - Ancient: History/Ancient.md
      - Modern: History/Modern.md
      - Timeline: History/Timeline.md
  - 'System':
    - Backgrounds: Cultures/Backgrounds/index.md
    - Races: Races/
    - Classes: Classes/
    - Conditions: Conditions/
    - Equipment: Equipment/
    - Feats: Feats/
    - 'Magic':
      - Items: Magic/Items/index.md
      - Spells: Magic/Spells/index.md
      - Tattoos: Magic/Tattoos/index.md
      - Undead Grafts: Magic/UndeadGrafts.md
      - Wild: Magic/Wild.md
    - 'Creatures':
      - Index: Creatures/index.md
      - List: Creatures/index-az.md
      - 'Types':
        - Aberrations: Creatures/index-aberration.md
        - Beasts: Creatures/index-beast.md
        - Celestials: Creatures/index-celestial.md
        - Constructs: Creatures/index-construct.md
        - Dragons: Creatures/index-dragon.md
        - Elementals: Creatures/index-elemental.md
        - Fey: Creatures/index-fey.md
        - Fiends: Creatures/index-fiend.md
        - Giants: Creatures/index-giant.md
        - Humanoids: Creatures/index-humanoid.md
        - Oozes: Creatures/index-ooze.md
        - Plants: Creatures/index-plant.md
        - Undead: Creatures/index-undead.md
  - 'About':
    - ... this site: about.md
    - ... my games: GameNotes.md
