name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Get config file
        run: cp Tools/Website/mkdocs.yml .
      - name: Run mkdocs
        run: mkdocs build

      # Upload content
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
